version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: 
      - .:/var/www/app_name
    links: 
      - postgres
      - redis
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: q15991599
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      REDIS_URL: redis://redis:6379
  postgres: 
    image: postgres:11.2
    volumes:
      - ./data/postgers:/var/lib/postgresql/data
  redis: 
    image: redis:5.0.5
    ports: 
     - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on: 
      - app
    ports: 
      - 80:80
