version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: 
      - .:/var/www/app_name
    depends_on: 
      - db
  db: 
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on: 
      - app
    ports: 
      - 80:80
